In [6]:
# 1)
#import numpy
import numpy as np

In [9]:
# 2)
array1 = np.arange(15,41,1)
array1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40])

In [10]:
# 2.1)
array2 = np.arange(10,26,1)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [32]:
array1.shape

(26,)

In [33]:
array2.shape

(16,)

The difference between the two arrays is the size of each array.

In [27]:
# 3)
even_array1 = np.arange(2,22,2)
even_array1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
# 3.1)
even_array2 = np.arange(34,44,2)
even_array2

array([34, 36, 38, 40, 42])

In [29]:
even_array1.shape

(10,)

In [30]:
even_array2.shape

(5,)

In [31]:
# 3.2)
stacked_array = np.hstack((even_array1, even_array2))
stacked_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 34, 36, 38, 40, 42])

In [34]:
# 4)
matrix = np.arange(0,36).reshape(6,6)

In [35]:
matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [37]:
# retrieve the intersetion of 3rd row and 2nd column
matrix[2][1]

13

In [38]:
# 4.1)
std_matrix = np.random.standard_normal((5,2))
std_matrix

array([[-0.12254719, -0.87952532],
       [-0.77524145, -0.47429243],
       [ 0.12916459,  0.33480185],
       [-1.01285422, -0.61505665],
       [-1.06271849,  1.50517303]])

In [39]:
# 4.2)
std_matrix[-1][-1]

1.505173030980929

In [41]:
# 5 a
np.min(std_matrix)

-1.0627184872900652

In [42]:
# 5 b
np.max(std_matrix)

1.505173030980929

In [43]:
# 5 c
np.std(std_matrix)

0.7522277338975771

In [44]:
# 5 d
np.var(std_matrix)

0.5658465636446841

In [45]:
# 5 e
np.mean(std_matrix)

-0.29730962765990937